name = "lean-excercises"
version = "0.2.0"
keywords = ["math"]
defaultTargets = ["LeanExcercises"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "LeanExcercises"
