name = "test1"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Test1"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Test1"
